---

- name: Verify Playbook
  hosts: all

  tasks:
    - name: Verify the role installed components properly
      ansible.builtin.include_role:
        name: demonpig.rclone
        tasks_from: verify
